### PR TITLE
Ensure event save works with different admin paths

### PR DESCRIPTION
**Pull request by jonmifsud**
Removal of hardcoded symphony path, and using the correct context variable for the complete admin path.

### CODE REVIEW

**Comment by wdebusschere** [comment]
Not yet everywhere ok, when i try to add an ETM to the generate recovery code event, i get an error, nothing happens. In symphony log:  User Notice: FrontendPageNotFoundException 1024 - The page you requested, <code>/symphony/extension/members/events/</code>, does not exist. on line 330 of /Users/xxx/Sites/xxx/symphony/lib/toolkit/class.frontendpage.php

**Comment by nitriques** [comment]
@wdebusschere Can you try to fire the event with the `?debug` querystring in your form's action attribute ?

**Comment by wdebusschere** [comment]
@nitriques This happens in the eventdetail page of the members_generate_recovery_code  in the symphony admin, when i try to choose the emailtemplate. Form action url is correct, but the post url is wrong http://localhost/xxx/symphony/extension/members/events/ should be http://localhost/xxx/customesymphony/extension/members/events/

Error is in L13 of https://github.com/symphonycms/members/edit/master/assets/members.events.js
url: Symphony.Context.get('symphony') + '/extension/members/events/',

**Comment by nitriques** [comment]
Well the code is correct, I do not get why you are having that value in there.
Can you run this in your dev tools and give me the full output ?

```js
Symphony.Context.get();
```

**Comment by wdebusschere** [comment]
Indeed this info is correct.


- lang:"en" 
- path:"/customsymphony" root: "http://localhost/xxx" . 
- route:"/blueprints/events/info/members_generate_recovery_code/"  
- symphony:"http://localhost/xxx/customsymphony"


The error in dev tools:
`symphony.min.js:9 POST http://localhost/xxx/symphony/extension/members/events/ 404 (Not Found)`

**Comment by nitriques** [comment]
So `Symphony.Context.get('symphony')` outputs "http://localhost/xxx/customsymphony" right ?

Are you seeing a 302 redirect before the 404 ? Because the code looks ok.

Are you able to load `http://localhost/xxx/customsymphony/extension/members/events/` ?

**Pull request merged**
