### PR TITLE
Escape data before using them in SQL

### LINKED ISSUE #286: Apostrophe in member name
We have a newly created user that's called `Director's uncut`. While front-end creation worked perfectly, it's neither possible to log into the front-end nor to filter by this name in the backend:

1. The front-end login just fails with the message that the user could not be found, no logs.
2. The backend logs an MySQL syntax error.

The SQL error reads 

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's uncut')

and highlights the following line:

```sql
`t104`.value IN ('Director's uncut')
```

This is obviously invalid.

We are using latest `integration` with latest Symphony (2.6.11).
Any ideas how to fix this?

/cc @brendo

### PR DESCRIPTION
**Pull request by nitriques**
This commit fixes a couple of possible SQLi errors.

Fixes #286

### CODE REVIEW

**Comment by nitriques** [comment]
@michael-e see #286 when Nils is searching for a user `Director's cut`

**Comment by nitriques** [comment]
Try to add some `'` in any input and see if it breaks.

**Comment by michael-e** [comment]
> Try to add some `'` in any input and see if it breaks.

Even without your fix, using plain Symphony 2.6.11 and Members 1.6.0, I added `'` to my Member name and was able to login nevertheless. Nothing broke. (However, the fact that my Member name was accepted doesn't feel very good, to be honest.)

I don't think that I understand all the issues well enough to do systematic testing here.

**Comment by nitriques** [comment]
No problems Jens thanks.

**Comment by nitriques** [comment]
@michael-e Nils also had problems with publish filtering I think. Nevertheless, the code needs those fixes.

**Comment by nitriques** [comment]
Just to make sure everybody's on the same page:

When I go in the members section, I filter by username with `'`, I get

image

The user does not see the end result, but can still do things like `'; DROP sym_entries; --`

Same thing happens with a datasource filtered by username usign `{$url-q}`. Issuing `/?q='` crashes the datasource. The end user does not see any errors message (you have to hit `/?q='&debug` to see it, but it still allows a remote user to issue random SQL commands.

image

**Comment by nitriques** [comment]
If  @nilshoerrmann could confirm that it fixes his problems, that would be cool ;)

**Comment by nilshoerrmann** [comment]
I sadly won't have time this week to look into this. Feel free to ping me again next week.

**Comment by michael-e** [comment]
@nitriques Thanks for the the explanation. It sounds like a severe issue to me, because it is not limited to backend users. We should release a hotfix version soon.

**Comment by nitriques** [comment]
Thanks @nilshoerrmann 

@michael-e 

> It sounds like a severe issue to me 

It is! I've warned everybody [last June](https://github.com/symphonycms/members/issues/286#issuecomment-307976160) but never got the chance to actually patch it :(

**Comment by nitriques** [comment]
Version [`1.7.0`](https://github.com/symphonycms/members/releases/tag/1.7.0) is out

**Pull request merged**
