### PR TITLE
Release 1.5

### PR DESCRIPTION
**Pull request by michael-e**
New release, marking Symphony 2.6 compatibility. Should be merged into master for an official release.

### CODE REVIEW

**Comment by michael-e** [comment]
@nitriques: Don't want to merge this PR myself — it's always good if a second person takes a look.

**Comment by nitriques** [comment]
> Don't want to merge this PR myself — it's always good if a second person takes a look.

I always try to do the same :) But after 7 days without any comments, I feel like I can do it.

**Comment by nitriques** [comment]
And there you go: https://github.com/symphonycms/members/releases/tag/1.5

**Comment by michael-e** [comment]
Thanks!

**Pull request merged**
