### PR TITLE
Fatal Error if Role within a section fix

### PR DESCRIPTION
**Pull request by andrewminton**
Discussion on issue here: https://github.com/symphonycms/members/issues/272

### CODE REVIEW

**Comment by nitriques** [comment]
Would you be kind enough to create a new version in the meta.xml file Andrew ?

Thanks! :)

**Comment by andrewminton** [comment]
Are we talking 1.5.1? bugfix right?

**Comment by nitriques** [comment]
Yup!

**Comment by andrewminton** [comment]
Hey @nitriques is the description good enough? I did think I could have elaborated 'Check for existence of role before returning canProcessEvent function. but Role permissions error is suitable.

**Comment by nitriques** [comment]
It's good enough! Thanks!

**Comment by nitriques** [comment]
Thanks again! https://github.com/symphonycms/members/releases/tag/1.5.1

**Pull request merged**
